openapi: 3.0.1
info:
  version: 1.0.0
  title: Authorization Tokens Accounts Portfolio Risk Score API
  description: 'Use the `oauth` endpoint to generate the secure, time-limited JSON Web Tokens (JWTs) used to authorize access to APIs and components.</br></br>

    To request a token, click Authorize and enter the following credentials:


    * Username - Your Client ID.

    * Password - Your Client Secret.'
servers:
- url: https://www.us-api.morningstar.com/token
  description: PROD US
- url: https://www.emea-api.morningstar.com/token
  description: PROD EMEA
- url: https://www.apac-api.morningstar.com/token
  description: PROD APAC
security:
- BasicAuth: []
tags:
- name: Portfolio Risk Score
paths:
  /portfolioanalysis/v1/risk-score:
    post:
      tags:
      - Portfolio Risk Score
      summary: Calculate risk score
      parameters:
      - name: langcult
        in: query
        description: ISO culture codes. If not provided, defaults to the language defined in the settings. Overrides the value in the Accept-Language HTTP Header.
        schema:
          type: string
          default: en-US
          enum:
          - en-US
          - en-CA
          - fr-CA
          x-enumDescriptions:
            en-US: US English
            en-CA: Canadian English
            fr-CA: Canadian French
      - name: countryID
        in: query
        description: ISO alpha-3 country codes.
        schema:
          type: string
          default: ''
          enum:
          - AUS
          - CAN
          - CHN
          - GBR
          - IND
          - JPN
          - USA
          x-enumDescriptions:
            AUS: Australia
            CAN: Canada
            CHN: China
            GBR: Great Britain
            IND: India
            JPN: Japan
            USA: United States of America
      requestBody:
        $ref: '#/components/requestBodies/RequestPortfolioRiskScore'
      responses:
        '200':
          $ref: '#/components/responses/ResponsePortfolioRiskScore'
        '400':
          $ref: '#/components/responses/ErrorResponse400'
        '403':
          $ref: '#/components/responses/ErrorResponse403'
        '413':
          $ref: '#/components/responses/ErrorResponse413'
        '500':
          $ref: '#/components/responses/ErrorResponse500'
components:
  responses:
    ErrorResponse413:
      description: '413: Request Entity Too Large'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
          examples:
            ErrorResponse413Example1:
              $ref: '#/components/examples/ErrorResponse413Example1'
            ErrorResponse413Example2:
              $ref: '#/components/examples/ErrorResponse413Example2'
    ErrorResponse403:
      description: '403: Forbidden'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
          examples:
            ErrorResponse413Example1:
              $ref: '#/components/examples/ErrorResponse403Example1'
            ErrorResponse413Example2:
              $ref: '#/components/examples/ErrorResponse403Example2'
            ErrorResponse413Example3:
              $ref: '#/components/examples/ErrorResponse403Example3'
    ResponsePortfolioRiskScore:
      description: '200: OK'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponsePortfolioRiskScore'
          examples:
            PortfolioOptimizerResponseExample1:
              $ref: '#/components/examples/PortfolioRiskScoreResponseExample1'
    ErrorResponse400:
      description: '400: Bad Request'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
          examples:
            ErrorResponse400Example1:
              $ref: '#/components/examples/ErrorResponse400Example1'
            ErrorResponse400Example2:
              $ref: '#/components/examples/ErrorResponse400Example2'
            ErrorResponse400Example3:
              $ref: '#/components/examples/ErrorResponse400Example3'
            ErrorResponse400Example4:
              $ref: '#/components/examples/ErrorResponse400Example4'
            ErrorResponse400Example5:
              $ref: '#/components/examples/ErrorResponse400Example5'
            ErrorResponse400Example6:
              $ref: '#/components/examples/ErrorResponse400Example6'
            ErrorResponse400Example7:
              $ref: '#/components/examples/ErrorResponse400Example7'
            ErrorResponse400Example8:
              $ref: '#/components/examples/ErrorResponse400Example8'
            ErrorResponse400Example9:
              $ref: '#/components/examples/ErrorResponse400Example9'
            ErrorResponse400Example10:
              $ref: '#/components/examples/ErrorResponse400Example10'
    ErrorResponse500:
      description: '500: Internal Server Error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
          examples:
            ErrorResponse500Example1:
              $ref: '#/components/examples/ErrorResponse500Example1'
  examples:
    ErrorResponse400Example8:
      summary: Bad Request - TotalValue Required
      value:
        statusCode: 400
        errorCode: 400.riskScore.106
        message: 'TotalValue is required when holdings are allocated by Weight. Invalid portfolio name: ''UK demo portfolio'''
        requestId: b646504b-f701-4c73-befa-f3cbbc0571e1
    PortfolioRiskScoreResponseExample1:
      summary: Portfolio Risk Score Output
      value:
        riskScores:
        - portfolio:
            name: TestPortfolio1
            riskScore: 74.30804031
            alignmentScore: 0
            rSquared: 0
            retainedWeightProxied: 0
            scoringMethodUsed: HBSA
            effectiveDate: '2024-01-31'
        metadata:
          requestId: f87f72c2-9a76-40f6-9118-a7be027eff9d
          time: '2024-02-26T15:29:16.8685342Z'
    ErrorResponse403Example3:
      summary: Forbidden - Not Authorized for Any CountryId
      value:
        statusCode: 403
        errorCode: 403.riskScore.007
        message: The user is not authorized for any countryId.
        requestId: 42b8be14-0ff7-440e-8ec6-e9f5a10e64d9
    ErrorResponse400Example3:
      summary: Bad Request - Mix of Weight and Value Passed in Request
      value:
        statusCode: 400
        errorCode: 400.riskScore.100
        message: 'Holdings must use either Weight or Value. UK demo portfolio. Holdings allocated by weight: 3, holdings allocated by value: 1'
        requestId: 34b98999-a882-42ce-96b1-0b216601d9e9
    ErrorResponse400Example9:
      summary: Bad Request - Multiple Input Currencies Provided
      value:
        statusCode: 400
        errorCode: 400.riskScore.108
        message: Only one input currency per request is supported.
        requestId: ce2889e2-151d-4360-9834-2cab1514c95c
    ErrorResponse403Example1:
      summary: Forbidden - Not Authorized for Specific CountryId
      value:
        statusCode: 403
        errorCode: 403.riskScore.005
        message: The user is not authorized for the countryId-USA.
        requestId: e922fdf6-d1ef-421b-aa21-6e9ced90d920
    ErrorResponse413Example2:
      summary: Request Entity Too Large - Max. Number of Holdings Exceeded
      value:
        statusCode: 413
        errorCode: 413.riskScore.102
        message: The total number of holdings in a portfolio exceeds the maximum limit of 250.
        requestId: 85e32d15-eb14-47ab-a224-320f03c2a5a9
    ErrorResponse400Example10:
      summary: Bad Request - Portfolio Total Value or Weight is 0
      value:
        statusCode: 400
        errorCode: 400.riskScore.109
        message: The total weight or value of a portfolio's valid holdings must be greater than 0.
        requestId: 1311dfa8-5e02-416f-a747-07d4675ad073
    ErrorResponse400Example5:
      summary: Bad Request - Missing Holdings Identifiers
      value:
        statusCode: 400
        errorCode: 400.riskScore.103
        message: 'There are holdings present in the portfolio that do not have an identifier. Invalid portfolio name: ''UK demo portfolio'''
        requestId: 1a1adb6f-de88-4b8b-b0ca-44448e027dfa
    ErrorResponse400Example2:
      summary: Bad Request - Unsupported countryId Value
      value:
        statusCode: 400
        errorCode: 400.riskScore.004
        message: CountryId USA is not currently supported. Please contact your administrator.
        requestId: b2370e75-27d1-4492-9e38-1c82bbf33165
    ErrorResponse403Example2:
      summary: Forbidden - Not Authorized for Default CountryId
      value:
        statusCode: 403
        errorCode: 403.riskScore.006
        message: The user is not authorized for the default countryId-USA.
        requestId: c784bacf-37dd-4d02-83e2-9001ab5fcf39
    ErrorResponse400Example6:
      summary: Bad Request - No Holdings in Portfolio
      value:
        statusCode: 400
        errorCode: 400.riskScore.104
        message: 'No holdings present in portfolio. Invalid portfolio name: ''UK demo portfolio'''
        requestId: 754f49b8-6415-4b98-8e49-289f280100f7
    ErrorResponse500Example1:
      summary: Internal Server Error
      value:
        statusCode: 500
        errorCode: 500.riskScore.008
        message: Internal Server Error
        requestId: 6bc61555-c0f1-4d7c-b912-ec56a94cc620
    ErrorResponse400Example4:
      summary: Bad Request - Portfolio TotalWeight Not Equal to 100
      value:
        statusCode: 400
        errorCode: 400.riskScore.101
        message: 'The total weight of the portfolio''s holdings does not add up to 100. Invalid portfolio name: ''UK demo portfolio'''
        requestId: 85e32d15-eb14-47ab-a224-320f03c2a5a9
    ErrorResponse400Example1:
      summary: Bad Request - Unsupported langcult Value
      value:
        statusCode: 400
        errorCode: 400.riskScore.001
        message: LangCult fr-FR is not currently supported. Please contact your administrator.
        requestId: 6bc61555-c0f1-4d7c-b912-ec56a94cc628
    ErrorResponse400Example7:
      summary: Bad Request - No Portfolios in Request
      value:
        statusCode: 400
        errorCode: 400.riskScore.105
        message: No portfolios present in request
        requestId: 037f8480-e6dd-4d69-900d-506fe28355db
    PortfolioRiskScoreRequestExample1:
      summary: Portfolio Risk Score Input
      value:
        Portfolios:
        - name: TestPortfolio1
          currency: USD
          totalValue: 1000
          holdings:
          - SecurityId: FOUSA05H5F
            Weight: 60
          - SecurityId: FOUSA04BCR
            Weight: 40
    ErrorResponse413Example1:
      summary: Request Entity Too Large - Max. Number of Portfolios Exceeded
      value:
        statusCode: 413
        errorCode: 413.riskScore.003
        message: Risk Score is only supported with two portfolios
        requestId: 036824d0-2cff-4783-8ae0-e63ccf1e4d30
  schemas:
    OutputPortfolioRiskScore:
      type: object
      properties:
        portfolio:
          $ref: '#/components/schemas/OutputPortfolio'
        metadata:
          $ref: '#/components/schemas/OutputMetadata'
      additionalProperties: false
    ResponsePortfolioRiskScore:
      type: object
      properties:
        riskScores:
          type: array
          items:
            $ref: '#/components/schemas/OutputPortfolioRiskScore'
          description: An array that displays the risk scores of scored portfolios.
          nullable: true
        metadata:
          $ref: '#/components/schemas/OutputMetadata'
      additionalProperties: false
      description: RiskScore response
    OutputPortfolio:
      type: object
      properties:
        name:
          type: string
          description: Portfolio name
          nullable: true
        riskScore:
          type: number
          description: A measure of the risk of portfolios, and the products they are comprised of.
          format: double
          nullable: true
        alignmentScore:
          type: number
          description: The proportion of the Risk Score associated with active risk.
          format: double
          nullable: true
        rSquared:
          type: number
          description: The proportion of a portfolio's variance that is explained by the asset class exposure.
          format: double
          nullable: true
        retainedWeightProxied:
          type: number
          description: This attribute refers to the total weight corresponding to the holdings we recognize in a portfolio.
          format: double
          nullable: true
        scoringMethodUsed:
          type: string
          description: Scoring method used - HBSA / RBSA
          nullable: true
        effectiveDate:
          type: string
          description: Date the portfolio was queried.
          nullable: true
      additionalProperties: false
    InputPortfolio:
      description: Object representing a portfolio to be analysed. Each holding must specify a security identifier and one of `Weight` or `Value`to define its allocation. `TotalValue` is required when holdings use `Weight`. Maximum of 250 holdings per portfolio.
      required:
      - Currency
      - Holdings
      - Name
      type: object
      properties:
        Name:
          description: Portfolio name.
          type: string
        TotalValue:
          description: Total market value of the portfolio in the portfolio currency. Required when holdings use `Weight`.
          type: number
          format: double
          minimum: 1
          example: 20000
        Currency:
          description: Portfolio currency. Accepted values are ISO 4217 currency codes.
          type: string
          enum:
          - AUD
          - CAD
          - CNY
          - EUR
          - GBP
          - INR
          - JPY
          - USD
          x-enumDescriptions:
            AUD: Australian Dollar
            CAD: Canadian Dollar
            CNY: Chinese Yuan
            EUR: Euro
            GBP: British Pound Sterling
            INR: Indian Rupee
            JPY: Japanese Yen
            USD: United States Dollar
          example: USD
        Holdings:
          description: List of portfolio holdings. Maximum of 250 holdings per portfolio.
          type: array
          maxItems: 250
          minItems: 1
          items:
            $ref: '#/components/schemas/InputPortfolioHolding'
    RequestPortfolioRiskScore:
      type: object
      properties:
        Portfolios:
          type: array
          items:
            $ref: '#/components/schemas/InputPortfolio'
          description: List of portfolios with holdings. A maximum of two portfolios can be passed in the request.
          maxItems: 2
          nullable: true
      additionalProperties: false
    InputPortfolioHolding:
      description: 'Each holding requires a security identifier and a position size. For the identifier, pass one of: `SecurityId`, `CUSIP`, `FundCode`, `ISIN`, `PerformanceId`, or `TradingSymbol`. If multiple identifiers are provided for a single security, `SecurityId` takes priority; if `SecurityId` is absent, the last identifier listed in the object is used. For the position size, pass one of: `Weight` or `Value`.'
      type: object
      properties:
        SecurityId:
          description: Morningstar unique identifier of a security. Use `CASH%0.000` for cash positions.
          type: string
          example: FOUSA00DFS,CASH%0.000
        Weight:
          description: Holding weight as a percentage of portfolio total. All holding weights must sum to 100. Requires `TotalValue` to be set on the portfolio.
          minimum: 1
          maximum: 100
          example: 60
          type: number
          format: double
        Value:
          description: Market value of the holding in the portfolio currency.
          minimum: 1
          example: 25000
          type: number
          format: double
        PerformanceId:
          description: Morningstar performance identifier of a security.
          type: string
          example: 0P00002QN3
        CUSIP:
          description: CUSIP identifier of a security.
          type: string
          example: 09251T103
        ISIN:
          description: ISIN identifier of a security.
          type: string
          example: US0378331005
        TradingSymbol:
          description: Trading symbol (ticker) of a security.
          type: string
          example: MDLOX
        FundCode:
          description: Fund code identifier of a security. Specific to Thai markets.
          type: string
          example: ABG
    OutputMetadata:
      type: object
      description: Metadata model.
      properties:
        requestId:
          type: string
          description: Unique identifier of the request, useful for support and debugging.
          nullable: true
          example: 33f0a7e0-8088-4ea9-b26e-d356b888e7de
        time:
          type: string
          format: date-time
          description: ISO 8601 timestamp indicating when the response was generated.
          readOnly: true
          example: '2024-05-14T16:41:24.4418482Z'
    ResponseError:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        errorCode:
          type: string
          description: Custom error code
          nullable: true
        message:
          type: string
          description: Message
          nullable: true
        requestId:
          type: string
          description: RequestId
          nullable: true
      additionalProperties: false
      description: Error details
  requestBodies:
    RequestPortfolioRiskScore:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestPortfolioRiskScore'
          examples:
            PortfolioRiskScoreRequestExample1:
              $ref: '#/components/examples/PortfolioRiskScoreRequestExample1'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
